create table work_sessions (
  id bigint generated by default as identity primary key,
  slack_user_id text not null,
  slack_user_name text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  duration_minutes integer,
  created_at timestamptz not null default now(),
  constraint ended_at_after_started_at check (
    ended_at is null or ended_at >= started_at
  ),
  constraint duration_minutes_is_not_negative check (
    duration_minutes is null or duration_minutes >= 0
  )
);

create unique index one_active_session_per_user
on work_sessions (slack_user_id)
where ended_at is null;

create index work_sessions_user_started_at_idx
on work_sessions (slack_user_id, started_at desc);

create table app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
